export const posts = {
    "tsunami-de-libertad-o-alienacion-tecnificada": {
        title: "¿Tsunami de libertad o alienación tecnificada?",
        date: "2019-12-28T19:41",
        tags: ['General'],
        language: "es",
    },
    "on-the-verge-of-a-new-era-freedom-tsunami-or-schemed-alienation": {
        title: "On the verge of a new era: freedom tsunami or schemed alienation?",
        date: "2019-12-16T18:36",
        tags: ["General"],
        language: "en",
    },
    "las-noticias-son-para-la-mente-lo-que-la-comida-basura-para-el-cuerpo": {
        title: "Las noticias son para la mente lo que la comida basura para el cuerpo",
        date: "2019-01-28T22:15",
        tags: ["General"],
        language: "es",
    },
    "tecnologia-inteligente-ciudades-idiotas": {
        title: "Tecnología inteligente, ciudades idiotas",
        date: "2015-11-24T16:01",
        tags: ["General"],
        language: "en",
    },
    "me-entrevistan-en-el-heraldo-de-colombia": {
        title: "Me entrevistan en El Heraldo de Colombia",
        date: "2012-03-31T00:07",
        tags: ["General"],
        language: "es",
    },
    "fighting-email": {
        title: "Fighting email",
        date: "2012-01-16T13:26",
        tags: ["General"],
        language: "en",
    },
    "dimitrij-email-cz": {
        title: "dimitrij@email.cz",
        date: "2011-02-06T08:04",
        tags: ["General"],
        language: "en",
    },
    "terrorismo": {
        title: "Terrorismo",
        date: "2010-03-22T23:39",
        tags: ["General"],
        language: "es",
    },
    "fe": {
        title: "Fe",
        date: "2009-12-12T16:06",
        tags: ["Dios ha muerto"],
        language: "es",
    },
    "intelligence": {
        title: "Intelligence",
        date: "2009-02-17T01:14",
        tags: ["General"],
        language: "en",
    },
    "downshifting": {
        title: "Downshifting",
        date: "2009-02-16T00:25",
        tags: ["General"],
        language: "en",
    },
    "feynman-on-religion": {
        title: "Feynman on religion",
        date: "2009-02-05T03:48",
        tags: ["General"],
        language: "en",
    },
    "ha-muerto-mikel-laboa": {
        title: "Ha muerto Mikel Laboa",
        date: "2008-12-02T01:03",
        tags: ["General"],
        language: "es",
    },
    "can-we-have-our-ball-back": {
        title: "Can we have our ball back?",
        date: "2008-11-24T23:16",
        tags: ["General"],
        language: "es",
    },
    "correo-electronico": {
        title: "Correo electrónico",
        date: "2008-10-28T02:29",
        tags: ["General"],
        language: "es",
    },
    "microsoft-word-ese-gran-desconocido": {
        title: "Microsoft Word: ese gran desconocido",
        date: "2008-10-07T08:49",
        tags: ["General"],
        language: "es",
    },
    "ernst-rutherford-hablando-sobre-niels-bohr": {
        title: "Ernst Rutherford hablando sobre Niels Bohr",
        date: "2008-09-15T23:59",
        tags: ["General"],
        language: "es",
    },
    "safari": {
        title: "Safari",
        date: "2008-07-12T23:34",
        tags: ["General"],
        language: "en",
    },
    "preguntas-de-un-obrero-que-lee": {
        title: "Preguntas de un obrero que lee",
        date: "2008-02-15T01:12",
        tags: ["General"],
        language: "es",
    },
    "por-que-tienen-las-horas-sesenta-minutos": {
        title: "¿Por qué tienen las horas sesenta minutos?",
        date: "2008-02-02T05:00",
        tags: ["General"],
        language: "es",
    },
    "asignatura-de-religion": {
        title: "¿Asignatura de religión?",
        date: "2008-01-28T23:42",
        tags: ["General"],
        language: "es",
    },
    "stockholm-syndrome": {
        title: "Stockholm syndrome",
        date: "2008-01-13T15:18",
        tags: ["General"],
        language: "en",
    },
    "conciencia": {
        title: "Conciencia",
        date: "2008-01-13T02:49",
        tags: ["General"],
        language: "es",
    },
    "la-identidad-de-euler": {
        title: "La identidad de Euler",
        date: "2008-01-06T21:05",
        tags: ["General"],
        language: "es",
    },
    "aprender-y-olvidar": {
        title: "Aprender y olvidar",
        date: "2008-01-02T13:25",
        tags: ["Idiomas"],
        language: "es",
    },
    "neue-slowenische-kunst": {
        title: "Neue Slowenische Kunst",
        date: "2007-12-30T18:05",
        tags: ["General"],
        language: "es",
    },
    "el-hombre-mas-sabio-del-mundo": {
        title: "El hombre más sabio del mundo",
        date: "2007-12-30T16:48",
        tags: ["General"],
        language: "es",
    },
    "copia-el-semanal-xl-a-stern": {
        title: "¿Copia El Semanal XL a Stern?",
        date: "2007-11-06T01:03",
        tags: ["General"],
        language: "es",
    },
    "nacionalismo-e-idioma": {
        title: "Nacionalismo e idioma",
        date: "2007-10-25T00:28",
        tags: ["Idiomas"],
        language: "es",
    },
    "otono-en-alemania": {
        title: "Otoño en Alemania",
        date: "2007-10-16T03:05",
        tags: ["General"],
        language: "es",
    },
    "me-debe-usted-cuarenta-francos": {
        title: "Me debe usted cuarenta francos",
        date: "2007-10-14T20:46",
        tags: ["Literatura"],
        language: "es",
    },
    "le-vent-nous-portera": {
        title: "Le vent nous portera",
        date: "2007-10-03T11:03",
        tags: ["Idiomas", "Poesía"],
        language: "fr",
    },
    "ciencia-para-explicar-la-religion": {
        title: "Ciencia para explicar la religión",
        date: "2007-09-26T01:07",
        tags: ["Dios ha muerto"],
        language: "es",
    },
    "la-fiesta-de-la-democracia": {
        title: "La fiesta de la democracia",
        date: "2007-09-22T18:03",
        tags: ["General"],
        language: "es",
    },
    "dias-de-28-horas": {
        title: "Días de 28 horas",
        date: "2007-08-16T12:19",
        tags: ["General"],
        language: "es",
    },
    "que-listo-es": {
        title: "Qué listo es",
        date: "2007-05-11T20:25",
        tags: ["General"],
        language: "es",
    },
    "mucho-cuidado": {
        title: "Mucho cuidado",
        date: "2007-05-11T08:34",
        tags: ["General"],
        language: "es",
    },
    "ostalgia": {
        title: "Ostalgia",
        date: "2007-05-09T01:07",
        tags: ["Idiomas", "Literatura", "Poesía"],
        language: "es",
    },
    "fud": {
        title: "FUD",
        date: "2007-05-02T17:56",
        tags: ["General"],
        language: "es",
    },
    "rir": {
        title: "Rir",
        date: "2007-04-28T00:19",
        tags: ["General"],
        language: "es",
    },
    "gott-nein-kirche-nein": {
        title: "Gott nein, Kirche nein",
        date: "2007-04-27T23:33",
        tags: ["Dios ha muerto"],
        language: "es",
    },
    "la-leccion-del-adios": {
        title: "La lección del adiós",
        date: "2007-04-10T00:17",
        tags: ["General"],
        language: "es",
    },
    "10-preguntas-para-un-cristiano-inteligente": {
        title: "10 preguntas que todo cristiano inteligente debería plantearse",
        date: "2007-04-06T18:01",
        tags: ["Dios ha muerto"],
        language: "es",
    },
    "la-donna-e-mobile": {
        title: "La donna è mobile",
        date: "2007-03-18T23:15",
        tags: ["General"],
        language: "es",
    },
    "quiero-toda-la-tierra": {
        title: "Quiero toda la tierra",
        date: "2007-03-18T20:50",
        tags: ["General"],
        language: "es",
    },
    "irgendwie-irgendwo-irgendwann": {
        title: "Irgendwie, irgendwo, irgendwann",
        date: "2007-03-15T01:14",
        tags: ["General"],
        language: "es",
    },
    "sonar-profundo": {
        title: "Sonar profundo",
        date: "2007-01-27T18:09",
        tags: ["General"],
        language: "la",
    },
    "siempre": {
        title: "Siempre",
        date: "2007-01-09T00:25",
        tags: ["General"],
        language: "es",
    },
    "der-wille-zur-macht": {
        title: "Der Wille zur Macht",
        date: "2007-01-08T01:09",
        tags: ["Dios ha muerto", "Literatura"],
        language: "es",
    },
    "besos": {
        title: "Besos",
        date: "2006-12-29T00:34",
        tags: ["General"],
        language: "es",
    },
    "sodade": {
        title: "Sodade",
        date: "2006-12-27T00:30",
        tags: ["Idiomas", "Poesía"],
        language: "pt",
    },
    "si-quiero-conocer": {
        title: "Si quiero conocer",
        date: "2006-12-07T00:46",
        tags: ["Literatura"],
        language: "es",
    },
    "el-banquero-anarquista": {
        title: "El banquero anarquista",
        date: "2006-11-22T01:30",
        tags: ["Literatura"],
        language: "es",
    },
    "dura-dura-lex": {
        title: "Dura, dura lex",
        date: "2006-11-07T23:18",
        tags: ["General"],
        language: "es",
    },
    "ragioni-per-investire-in-italia": {
        title: "Due grandi ragioni per investire in Italia",
        date: "2006-10-31T00:32",
        tags: ["General"],
        language: "it",
    },
    "agua-y-aceite": {
        title: "Agua y aceite",
        date: "2006-10-22T23:40",
        tags: ["General"],
        language: "es",
    },
    "about-inner-revelations": {
        title: "About \"inner revelations\"...",
        date: "2006-09-21T15:42",
        tags: ["Dios ha muerto"],
        language: "en",
    },
    "pueblo-de-dios-nuevos-capitulos": {
        title: "Pueblo de Dios, nuevos capítulos",
        date: "2006-08-29T23:34",
        tags: ["Dios ha muerto"],
        language: "es",
    },
    "in-grog-we-trust": {
        title: "In Grog we trust",
        date: "2006-08-28T14:37",
        tags: ["General"],
        language: "es",
    },
    "la-locomotora-de-praga": {
        title: "La locomotora de Praga",
        date: "2006-08-10T20:28",
        tags: ["general"],
        language: "es",
    },
    "el-rio": {
        title: "El río",
        date: "2006-08-07T23:49",
        tags: ["Literatura"],
        language: "es",
    },
    "todas-as-cartas-de-amor": {
        title: "Todas as cartas de amor",
        date: "2006-08-07T20:32",
        tags: ["Literatura", "Poesía"],
        language: "pt",
    },
    "languages": {
        title: "Languages",
        date: "2006-08-07T20:27",
        tags: ["Idiomas"],
        language: "en",
    },
    "ateismo": {
        title: "Ateísmo",
        date: "2006-07-09T01:02",
        tags: ["Dios ha muerto"],
        language: "es",
    },
    "medios": {
        title: "Medios",
        date: "2006-06-30T15:40",
        tags: ["Literatura", "General"],
        language: "es",
    },
    "navegar": {
        title: "Navegar",
        date: "2006-06-25T15:19",
        tags: ["Literatura", "Dios ha muerto"],
        language: "la",
    },
    "cuando-te-vieres-ante-la-luz-de-su-hermosura": {
        title: "Cuando te vieres ante la luz de su hermosura",
        date: "2006-06-24T21:56",
        tags: ["Literatura"],
        language: "es",
    },
    "el-sol-grande-en-la-era": {
        title: "El Sol grande en la era...",
        date: "2006-06-22T23:34",
        tags: ["Poesía"],
        language: "es",
    },
    "que-le-pedirias-al-presidente": {
        title: "¿Qué le pedirías al Presidente?",
        date: "2006-06-22T22:57",
        tags: ["General"],
        language: "es",
    },
    "el-lugar-maldito": {
        title: "El lugar maldito",
        date: "2006-06-16T22:07",
        tags: ["Dios ha muerto", "Literatura"],
        language: "es",
    },
    "esta-bien-esta-mal": {
        title: "Está bien, está mal",
        date: "2006-06-16T16:01",
        tags: ["Dios ha muerto"],
        language: "es",
    },
    "vinas-verdes-junto-al-mar": {
        title: "Viñas verdes junto al mar",
        date: "2006-06-11T20:43",
        tags: ["Idiomas", "Poesía"],
        language: "ca",
    },
    "poemas-palindromicos-en-euskera": {
        title: "Poemas palindrómicos en euskera",
        date: "2006-06-11T16:23",
        tags: ["Idiomas", "Poesía"],
        language: "eu",
    },
    "o-sentimento-do-mundo": {
        title: "O sentimento do mundo",
        date: "2006-06-11T14:46",
        tags: ["Idiomas", "Poesía"],
        language: "pt",
    },
}
