export const posts = {
    "tsunami-de-libertad-o-alienacion-tecnificada": {
        title: "¿Tsunami de libertad o alienación tecnificada?",
        description: "Asistimos a un papel inédito de la tecnología en el empoderamiento de las revueltas sociales. ¿Son eficaces las leyes del siglo XX para las protestas del XXI?",
        date: "2019-12-28T19:41",
        tags: ['General'],
        language: "es",
    },
    "on-the-verge-of-a-new-era-freedom-tsunami-or-schemed-alienation": {
        title: "On the verge of a new era: freedom tsunami or schemed alienation?",
        description: "We have front row seats to an exciting historical moment, seeing the role of technology in empowering social unrest. Are 20th century responses efficient solutions to 21st century protests?",
        date: "2019-12-16T18:36",
        tags: ["General"],
        language: "en",
    },
    "las-noticias-son-para-la-mente-lo-que-la-comida-basura-para-el-cuerpo": {
        title: "Las noticias son para la mente lo que la comida basura para el cuerpo",
        description: "Las noticias satisfacen fugazmente tu apetito de espectáculo y entretenimiento, pero luego te dejan insatisfecho y desinformado. Las noticias son solo calorías.",
        date: "2019-01-28T22:15",
        tags: ["General"],
        language: "es",
    },
    "tecnologia-inteligente-ciudades-idiotas": {
        title: "Tecnología inteligente, ciudades idiotas",
        description: "Recibo en mi teléfono mensajes inmediatos de la Estación Espacial y fotos instantáneas de los valles de Plutón, pero en dos meses nadie del Ayuntamiento de Santander ha sido capaz de responderme a un correo.",
        date: "2015-11-24T16:01",
        tags: ["General"],
        language: "en",
    },
    "me-entrevistan-en-el-heraldo-de-colombia": {
        title: "Me entrevistan en El Heraldo de Colombia",
        description: "Hoy recibí un cordial correo de la responsable de la sección de política económica del diario colombiano El Heraldo.",
        date: "2012-03-31T00:07",
        tags: ["General"],
        language: "es",
    },
    "fighting-email": {
        title: "Fighting email",
        description: "My whole relationship with email had to be completely rethought.",
        date: "2012-01-16T13:26",
        tags: ["General"],
        language: "en",
    },
    "dimitrij-email-cz": {
        title: "dimitrij@email.cz",
        description: "Giving up on 77.75.72.42.",
        date: "2011-02-06T08:04",
        tags: ["General"],
        language: "en",
    },
    "terrorismo": {
        title: "Terrorismo",
        description: "Los políticos clasifican los problemas en dos grandes tipos: aquellos que se solucionan por sí sólos con un poco de tiempo, y los que no tienen solución.",
        date: "2010-03-22T23:39",
        tags: ["General"],
        language: "es",
    },
    "fe": {
        title: "Fe",
        description: "Una relación exhaustiva de todos los estudios científicos conectados con la religión",
        date: "2009-12-12T16:06",
        tags: ["Dios ha muerto"],
        language: "es",
    },
    "intelligence": {
        title: "Intelligence",
        description: "You can use your intelligence to be stupid.",
        date: "2009-02-17T01:14",
        tags: ["General"],
        language: "en",
    },
    "downshifting": {
        title: "Downshifting",
        description: "Escaping the rat race of obsessive materialism and focusing life goals on personal fulfillment and relationship building instead of the all-consuming pursuit of economic success.",
        date: "2009-02-16T00:25",
        tags: ["General"],
        language: "en",
    },
    "feynman-on-religion": {
        title: "Feynman on religion",
        description: "About living with doubt, uncertainty and not knowing. It is much more interesting to live not knowing than to have answers which might be wrong.",
        date: "2009-02-05T03:48",
        tags: ["General"],
        language: "en",
    },
    "ha-muerto-mikel-laboa": {
        title: "Ha muerto Mikel Laboa",
        description: "No os dejéis engañar / Con que la vida es poco. / Bebedla a grandes tragos / porque no os bastará / cuando hayáis de perderla.",
        date: "2008-12-02T01:03",
        tags: ["General"],
        language: "es",
    },
    "can-we-have-our-ball-back": {
        title: "Can we have our ball back?",
        description: "Pintada en el Muro de Berlín.",
        date: "2008-11-24T23:16",
        tags: ["General"],
        language: "es",
    },
    "correo-electronico": {
        title: "Correo electrónico",
        description: "En los 300 días que han transcurrido de este año, he escrito y enviado 2.622 correos electrónicos.",
        date: "2008-10-28T02:29",
        tags: ["General"],
        language: "es",
    },
    "microsoft-word-ese-gran-desconocido": {
        title: "Microsoft Word: ese gran desconocido",
        description: "Leyendo una resolución de la AEPD me doy cuenta de que parece que alguien está teniendo serios problemas con los autoenlaces de Microsoft Word…",
        date: "2008-10-07T08:49",
        tags: ["General"],
        language: "es",
    },
    "ernst-rutherford-hablando-sobre-niels-bohr": {
        title: "Ernst Rutherford hablando sobre Niels Bohr",
        description: "«Estaba a punto de poner un cero a un estudiante por la respuesta que había dado en un problema de física, pese a que este afirmaba con rotundidad que su respuesta era absolutamente acertada».",
        date: "2008-09-15T23:59",
        tags: ["General"],
        language: "es",
    },
    "safari": {
        title: "Safari",
        description: "The word \"safari\" means \"journey\" in Swahili.",
        date: "2008-07-12T23:34",
        tags: ["General"],
        language: "en",
    },
    "preguntas-de-un-obrero-que-lee": {
        title: "Preguntas de un obrero que lee",
        description: "¿Quién construyó Tebas, la de las siete puertas? En los libros se mencionan los nombres de los reyes. ¿Acaso los reyes arrastraron las piedras?",
        date: "2008-02-15T01:12",
        tags: ["General"],
        language: "es",
    },
    "por-que-tienen-las-horas-sesenta-minutos": {
        title: "¿Por qué tienen las horas sesenta minutos?",
        description: "Las horas de nuestros días tienen sesenta minutos porque un comerciante babilónico se dio cuenta de cómo podía contar el género mucho más deprisa, en el estruendo de un día de mercado en Mesopotamia hace 4.000 años.",
        date: "2008-02-02T05:00",
        tags: ["General"],
        language: "es",
    },
    "asignatura-de-religion": {
        title: "¿Asignatura de religión?",
        description: "No vengas a rezar a mi escuela y yo no iré a pensar a tu iglesia.",
        date: "2008-01-28T23:42",
        tags: ["General"],
        language: "es",
    },
    "stockholm-syndrome": {
        title: "Stockholm syndrome",
        description: "«Olsson received many admiring letters from women who found him attractive. He later married to one of his female admirers».",
        date: "2008-01-13T15:18",
        tags: ["General"],
        language: "en",
    },
    "conciencia": {
        title: "Conciencia",
        description: "¡No seamos cobardes con nuestros actos; no nos avergoncemos después de haberlos realizado! El remordimiento de conciencia es algo indecoroso.",
        date: "2008-01-13T02:49",
        tags: ["General"],
        language: "es",
    },
    "la-identidad-de-euler": {
        title: "La identidad de Euler",
        description: "¿Es la identidad de Euler la ecuación más bella de la historia de las matemáticas?",
        date: "2008-01-06T21:05",
        tags: ["General"],
        language: "es",
    },
    "aprender-y-olvidar": {
        title: "Aprender y olvidar",
        description: "Cuando aquella chica puso Trieste en sus labios, disparó en mi cabeza un mecanismo de evolución neuronal que ha durado un millón de años y que reproduce rápidamente un \"playback\" de una canción idiota de Raffaella Carrà.",
        date: "2008-01-02T13:25",
        tags: ["Idiomas"],
        language: "es",
    },
    "neue-slowenische-kunst": {
        title: "Neue Slowenische Kunst",
        description: "En 1987 las autoridades yugoslavas convocaron un concurso para elegir el cartel que conmemoraría el Día de la Juventud Yugoslava, efeméride del nacimiento del mariscal Tito.",
        date: "2007-12-30T18:05",
        tags: ["General"],
        language: "es",
    },
    "el-hombre-mas-sabio-del-mundo": {
        title: "El hombre más sabio del mundo",
        description: "«El hombre más sabio que he conocido en toda mi vida no sabía leer ni escribir. A las cuatro de la madrugada, cuando la promesa de un nuevo día aún venía por tierras de Francia, se levantaba del catre y salía al campo».",
        date: "2007-12-30T16:48",
        tags: ["General"],
        language: "es",
    },
    "copia-el-semanal-xl-a-stern": {
        title: "¿Copia El Semanal XL a Stern?",
        description: "A la izquierda, la portada del 12 de julio del semanario alemán Stern. A la derecha, la primera plana del ejemplar del 4 de noviembre de la revista española El Semanal XL, que se regala con los diarios de Vocento.",
        date: "2007-11-06T01:03",
        tags: ["General"],
        language: "es",
    },
    "nacionalismo-e-idioma": {
        title: "Nacionalismo e idioma",
        description: "España tiene 45 millones de habitantes y cinco lenguas oficiales: el castellano, el catalán, el gallego, el vasco y el aranés. Más de 8 millones de españoles hablan dos de estas lenguas oficiales.",
        date: "2007-10-25T00:28",
        tags: ["Idiomas"],
        language: "es",
    },
    "otono-en-alemania": {
        title: "Otoño en Alemania",
        description: "Brigitte Mohnhaupt ha sido puesta en libertad condicional en marzo, tras ser condenada a cinco cadenas perpetuas y pasar finalmente 24 años en prisión.",
        date: "2007-10-16T03:05",
        tags: ["General"],
        language: "es",
    },
    "me-debe-usted-cuarenta-francos": {
        title: "Me debe usted cuarenta francos",
        description: "Los dadaístas construían poesía y literatura dificílmente clasificable haciendo trizas hojas de periódico y recomponiéndolas al azar después.",
        date: "2007-10-14T20:46",
        tags: ["Literatura"],
        language: "es",
    },
    "le-vent-nous-portera": {
        title: "Le vent nous portera",
        description: "Ton message à la grande ourse / Et la trajectoire de la course / A l'instantané de velours / Même s'il ne sert à rien. / Le vent l'emportera. / Tout disparaîtra. / Le vent nous portera.",
        date: "2007-10-03T11:03",
        tags: ["Idiomas", "Poesía"],
        language: "fr",
    },
    "ciencia-para-explicar-la-religion": {
        title: "Ciencia para explicar la religión",
        description: "Mira al Sol y velo como lo han visto antes todos los demás humanos que a lo largo de las eras han alzado la mirada al firmamento. Y en su luz verás, como vieron ellos, al único Dios que desde la inmensidad del cielo gobierna el universo.",
        date: "2007-09-26T01:07",
        tags: ["Dios ha muerto"],
        language: "es",
    },
    "la-fiesta-de-la-democracia": {
        title: "La fiesta de la democracia",
        description: "Lizartza es un pequeño municipio de Guipúzcoa. Tiene un censo de 509 vecinos. Desde 1979 hasta el 2003 ha sido gobernado, bajo distintas siglas, por la izquierda abertzale.",
        date: "2007-09-22T18:03",
        tags: ["General"],
        language: "es",
    },
    "dias-de-28-horas": {
        title: "Días de 28 horas",
        description: "«Modifiqué artificialmente mi ritmo circadiano. Me \"fabriqué\" una semana de 6 días de 28 horas cada uno. Mi intención era aumentar mi productividad y, sobre todo, hacer un experimento físico y psicológico de resultados impredecibles».",
        date: "2007-08-16T12:19",
        tags: ["General"],
        language: "es",
    },
    "que-listo-es": {
        title: "Qué listo es",
        description: "Fragmento de una conversación escuchada en el pasillo de un hospital.",
        date: "2007-05-11T20:25",
        tags: ["General"],
        language: "es",
    },
    "mucho-cuidado": {
        title: "Mucho cuidado",
        description: "Me ha contado mi abogado / que si no quiero ir al trullo / he de poner mucho cuidado / en no juntarme con capullos.",
        date: "2007-05-11T08:34",
        tags: ["General"],
        language: "es",
    },
    "ostalgia": {
        title: "Ostalgia",
        description: "Es lo que tienen las revoluciones, que destruyen Estados y construyen palabras. Aunque sean revoluciones sin fusiles, como la que acabó con Checoslovaquia, o con claveles en los fusiles, como el 25 de abril portugués.",
        date: "2007-05-09T01:07",
        tags: ["Idiomas", "Literatura", "Poesía"],
        language: "es",
    },
    "fud": {
        title: "FUD",
        description: "El Gobierno de Cataluña no sanciona a los comercios \"que ponen los letreros de sus tiendas en castellano\", sino sólo a aquellos que no lo hacen en catalán. No es lo mismo: ni siquiera es parecido. Es más, es muy diferente.",
        date: "2007-05-02T17:56",
        tags: ["General"],
        language: "es",
    },
    "rir": {
        title: "Rir",
        description: "Receta para un experimento dadaísta.",
        date: "2007-04-28T00:19",
        tags: ["General"],
        language: "es",
    },
    "gott-nein-kirche-nein": {
        title: "Gott nein, Kirche nein",
        description: "«Le comunico que en este Obispado se ha recibido su escrito, en el que expresa su abandono de la Iglesia Católica».",
        date: "2007-04-27T23:33",
        tags: ["Dios ha muerto"],
        language: "es",
    },
    "la-leccion-del-adios": {
        title: "La lección del adiós",
        description: "Tenía este billete de tren y el recuerdo melancólico de una despedida en el andén 21 de la estación central de Zurich. Me faltaba una canción, y ayer la encontré.",
        date: "2007-04-10T00:17",
        tags: ["General"],
        language: "es",
    },
    "10-preguntas-para-un-cristiano-inteligente": {
        title: "10 preguntas que todo cristiano inteligente debería plantearse",
        description: "Si eres un cristiano instruido e inteligente me gustaría plantearte una pregunta interesante: ¿has analizado alguna vez tu fe religiosa desde el punto de vista de tu educación universitaria?",
        date: "2007-04-06T18:01",
        tags: ["Dios ha muerto"],
        language: "es",
    },
    "la-donna-e-mobile": {
        title: "La donna è mobile",
        description: "La mujer es cambiante como una pluma en el viento / cambia de palabra y de pensamiento. / Es siempre mísero el que en ella confía / y le entrega incauto el corazón",
        date: "2007-03-18T23:15",
        tags: ["General"],
        language: "es",
    },
    "quiero-toda-la-tierra": {
        title: "Quiero toda la tierra",
        description: "A través de una de esas películas que hacen pensar he llegado a \"Quiero toda la tierra más el 5%\", una interesante reflexión en forma de cuento breve sobre la historia del sistema bancario.",
        date: "2007-03-18T20:50",
        tags: ["General"],
        language: "es",
    },
    "irgendwie-irgendwo-irgendwann": {
        title: "Irgendwie, irgendwo, irgendwann",
        description: "En los últimos tiempos han sucedido tres cosas tales que cada una de ellas ha estado suficientemente fuera de lo común como para ser, por sí misma, todo un acontecimiento singular.",
        date: "2007-03-15T01:14",
        tags: ["General"],
        language: "es",
    },
    "sonar-profundo": {
        title: "Sonar profundo",
        description: "«Cualquier cosa dicha en latín suena profunda».",
        date: "2007-01-27T18:09",
        tags: ["General"],
        language: "la",
    },
    "siempre": {
        title: "Siempre",
        description: "Io sempre vinco.",
        date: "2007-01-09T00:25",
        tags: ["General"],
        language: "es",
    },
    "der-wille-zur-macht": {
        title: "Der Wille zur Macht",
        description: "«Que Alá no te dé inteligencia, porque tendrás que ponerla al servicio de los poderosos, que Alá te dé poder, así los inteligentes trabajarán para ti».",
        date: "2007-01-08T01:09",
        tags: ["Dios ha muerto", "Literatura"],
        language: "es",
    },
    "besos": {
        title: "Besos",
        description: "He leído que los romanos tenían tres palabras diferentes para decir \"beso\". ¿Por qué hemos perdido estas palabras?",
        date: "2006-12-29T00:34",
        tags: ["General"],
        language: "es",
    },
    "sodade": {
        title: "Sodade",
        description: "Si me escribes, te escribiré. Si me olvidas, te olvidaré.",
        date: "2006-12-27T00:30",
        tags: ["Idiomas", "Poesía"],
        language: "pt",
    },
    "si-quiero-conocer": {
        title: "Si quiero conocer",
        description: "«Es preciso que soporte dos o tres orugas si quiero conocer a las mariposas».",
        date: "2006-12-07T00:46",
        tags: ["Literatura"],
        language: "es",
    },
    "el-banquero-anarquista": {
        title: "El banquero anarquista",
        description: "Demasiado largo para un artículo, pero demasiado breve para un libro. En \"El banquero anarquista\" Pessoa vuelve a la prosa y la pluma para explicar que el verdadero anarquismo comienza por la liberación solitaria de uno mismo, y que no es posible crear libertad sin ejercer al mismo tiempo la tiranía.",
        date: "2006-11-22T01:30",
        tags: ["Literatura"],
        language: "es",
    },
    "dura-dura-lex": {
        title: "Dura, dura lex",
        description: "Audiencia Nacional, Madrid, España. Hoy.",
        date: "2006-11-07T23:18",
        tags: ["General"],
        language: "es",
    },
    "ragioni-per-investire-in-italia": {
        title: "Due grandi ragioni per investire in Italia",
        description: "«L'Italia è ora una grande nazione per investire. Oggi abbiamo pochi comunisti e quelli che ci sono ancora negano di esserlo. Un'altra ragione per investire in Italia è che abbiamo belle segretarie, ragazze stupende».",
        date: "2006-10-31T00:32",
        tags: ["General"],
        language: "it",
    },
    "agua-y-aceite": {
        title: "Agua y aceite",
        description: "La escena de Bettino Craxi escoltado de los estudiantes enfurecidos que le lanzan monedas gritando \"ladro\" o \"buffone\" ha sido recordada hasta la saciedad por los medios de comunicación italianos.",
        date: "2006-10-22T23:40",
        tags: ["General"],
        language: "es",
    },
    "about-inner-revelations": {
        title: "About \"inner revelations\"...",
        description: "«Many inhabitants of lunatic asylums have an unshakable inner faith that they are Napoleon or, indeed, God himself. There is no doubting the power of such convictions for those that have them, but this is no reason for the rest of us to believe them».",
        date: "2006-09-21T15:42",
        tags: ["Dios ha muerto"],
        language: "en",
    },
    "pueblo-de-dios-nuevos-capitulos": {
        title: "Pueblo de Dios, nuevos capítulos",
        description: "¿Y tú?, ¿ya sintonizas en tu televisor la excitante programación de Vaticano TV?",
        date: "2006-08-29T23:34",
        tags: ["Dios ha muerto"],
        language: "es",
    },
    "in-grog-we-trust": {
        title: "In Grog we trust",
        description: "«El 20 de octubre de 1720, las tropas del Capitán Barnet, enviadas por el gobernador de Jamaica, capturaron a Rackham y su tripulación, la mayor parte de los cuales estaban borrachos y no opusieron resistencia».",
        date: "2006-08-28T14:37",
        tags: ["General"],
        language: "es",
    },
    "la-locomotora-de-praga": {
        title: "La locomotora de Praga",
        description: "Emil Zátopek asombró al mundo en los Juegos Olímpicos de Helsinki en 1952, ganando el oro en las competiciones de 5.000 y 10.000 metros, así como en la maratón; prueba en la que nunca antes había competido.",
        date: "2006-08-10T20:28",
        tags: ["general"],
        language: "es",
    },
    "el-rio": {
        title: "El río",
        description: "«¿También a ti te enseñó el río aquel secreto: que el tiempo no existe?»",
        date: "2006-08-07T23:49",
        tags: ["Literatura"],
        language: "es",
    },
    "todas-as-cartas-de-amor": {
        title: "Todas as cartas de amor",
        description: "Todas as palavras esdrúxulas, como os sentimentos esdrúxulos, são naturalmente ridículas.",
        date: "2006-08-07T20:32",
        tags: ["Literatura", "Poesía"],
        language: "pt",
    },
    "languages": {
        title: "Languages",
        description: "«To God I speak Spanish, to women Italian, to men French, and to my horse - German»",
        date: "2006-08-07T20:27",
        tags: ["Idiomas"],
        language: "en",
    },
    "ateismo": {
        title: "Ateísmo",
        description: "«Nunca tendreis suficiente madera para quemar el azar que mueve el mundo».",
        date: "2006-07-09T01:02",
        tags: ["Dios ha muerto"],
        language: "es",
    },
    "medios": {
        title: "Medios",
        description: "Lo leí en el prólogo de algún libro de Joseba Sarrionandía. Es la evolución de los titulares del principal periódico francés, Le Moniteur, durante el mes de marzo de 1815, cuando Napoleón huyó de la Isla de Elba para retomar Francia.",
        date: "2006-06-30T15:40",
        tags: ["Literatura", "General"],
        language: "es",
    },
    "navegar": {
        title: "Navegar",
        description: "«Navigare necesse est; vivere non est necesse»",
        date: "2006-06-25T15:19",
        tags: ["Literatura", "Dios ha muerto"],
        language: "la",
    },
    "cuando-te-vieres-ante-la-luz-de-su-hermosura": {
        title: "Cuando te vieres ante la luz de su hermosura",
        description: "«Anda, hijo —replicó don Quijote—, y no te turbes cuando te vieres ante la luz del sol de hermosura que vas a buscar. ¡Dichoso tú sobre todos los escuderos del mundo! Ten memoria, y no se te pase de ella cómo te recibe»",
        date: "2006-06-24T21:56",
        tags: ["Literatura"],
        language: "es",
    },
    "el-sol-grande-en-la-era": {
        title: "El Sol grande en la era...",
        description: "El sol grande en la era / tal vez sea el remedio… / No quiero quien me quiera, / que me amen me da tedio.",
        date: "2006-06-22T23:34",
        tags: ["Poesía"],
        language: "es",
    },
    "que-le-pedirias-al-presidente": {
        title: "¿Qué le pedirías al Presidente?",
        description: "«El presidente que se elija debería sanearlo todo —me comprende— cuando salgo me da hasta dolor de cabeza oler toda esta basura, quiero decir que la porquería está en todas partes, en fin…»",
        date: "2006-06-22T22:57",
        tags: ["General"],
        language: "es",
    },
    "el-lugar-maldito": {
        title: "El lugar maldito",
        description: "«El lugar maldito en que el cristianismo ha encovado sus huevos de basilisco será arrasado, y, como lugar infame de la tierra, constituirá el terror de toda la posteridad. En él se criarán serpientes venenosas».",
        date: "2006-06-16T22:07",
        tags: ["Dios ha muerto", "Literatura"],
        language: "es",
    },
    "esta-bien-esta-mal": {
        title: "Está bien, está mal",
        description: "«Está bien estudiar el Universo y dónde se originó. Pero no se debería profundizar en el origen en sí mismo, puesto que se trata del momento de la Creación y de la intervención de Dios.»",
        date: "2006-06-16T16:01",
        tags: ["Dios ha muerto"],
        language: "es",
    },
    "vinas-verdes-junto-al-mar": {
        title: "Viñas verdes junto al mar",
        description: "Vinyes verdes del meu cor… / Dins del cep s'adorm la tarda, / raïm negre, pàmpol d'or, /aigua, penyal i basarda. / Vinyes verdes del meu cor…",
        date: "2006-06-11T20:43",
        tags: ["Idiomas", "Poesía"],
        language: "ca",
    },
    "poemas-palindromicos-en-euskera": {
        title: "Poemas palindrómicos en euskera",
        description: "Dos poemas palindrómicos (simétricos) de Joseba Sarrionandía musicados por Mikel Laboa.",
        date: "2006-06-11T16:23",
        tags: ["Idiomas", "Poesía"],
        language: "eu",
    },
    "o-sentimento-do-mundo": {
        title: "O sentimento do mundo",
        description: "Não és tu -faculdade de sentir- um espaço / terminado por linhas ou superfícies / e não obstante chove sobre ti, na cidade.",
        date: "2006-06-11T14:46",
        tags: ["Idiomas", "Poesía"],
        language: "pt",
    },
}
